version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: project3-coworking
    CODE_BUILD_NUMBER: latest
    AWS_ACCOUNT_ID: 533806766642
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...
      - docker build --build-arg DB_USERNAME=postgres --build-arg DB_PASSWORD=DWfdlnyuJg -t project3-coworking:latest ./app/.
      - docker tag $IMAGE_REPO_NAME:$CODE_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODE_BUILD_NUMBER
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODE_BUILD_NUMBER
docker build --build-arg DB_USERNAME=postgres --build-arg DB_PASSWORD=DWfdlnyuJg -t  udacity-project3:$CODE_BUILD_NUMBER ./app/.